### ISSUE TITLE
Error while parsing: entity expansion has grown too large

### ISSUE THREAD

**Issue by chr15m** [feed2imap/feed2imap#10]
Seems to be a problem with Ruby's XML parser limits:

http://stackoverflow.com/questions/15593133/rexml-runtimeerror-entity-expansion-has-grown-too-large

Apparently a fix is to set:

REXML::Document.entity_expansion_text_limit

to something smaller.

**Comment by terceiro** [comment]
can you please provide a test case?

**Comment by chr15m** [comment]
Here is a large XML feed that triggers the issue:

[test-feed.xml.zip](https://github.com/feed2imap/feed2imap/files/310631/test-feed.xml.zip)

If I add these lines at the start of the feed2imap script (right after the hash-bang) it no longer fails:

```
require 'rexml/document'
REXML::Document.entity_expansion_text_limit=102400
```

**Comment by haegar** [comment]
I had the same problem with the feed from our internal confluence wiki - the workaround from @chr15m works fine.

**Comment by korelstar** [comment]
The problem occurred for me, too. Thanks for the hotfix, @chr15m - it works fine!
