### ISSUE TITLE
http://home.gna.org/feed2imap seems to be down

### ISSUE THREAD

**Issue by pmetzger** [feed2imap/feed2imap#19]
http://home.gna.org/feed2imap seems to be down, whether temporarily or permanently I can't say, so perhaps the README.md should include whatever information used to be there?

**Comment by anarcat** [comment]
gna.org was shutdown by their administrators. a partial archive of the site was created by the amazing archiveteam people:

http://www.archiveteam.org/index.php?title=Gna!

a 20GB zip archive of all projects up to F include a copy of the feed2imap files as well. might as well start using github as a home now...

**Comment by pintman** [comment]
Why not using github pages for the website? Would this be an option?
