### ISSUE TITLE
Trouble with feedparser

### ISSUE THREAD

**Issue by quite** [feed2imap/feed2imap#6]
I manage to install all from git, but running feed2imap-test gives errors: (or, actually, INFO!)

I, [2014-02-13T21:40:04.315877 #17553]  INFO -- : Error while parsing CNPQ: unknown encoding name - application/xml (failed 1 times)
I, [2014-02-13T21:40:04.322229 #17553]  INFO -- : Error while parsing XKCD: unknown encoding name - application/xml (failed 1 times)

**Comment by terceiro** [comment]
Hi, I can't reproduce this. Will close the issue for now; please reopen if this is still a problem.
