### ISSUE TITLE
include-images not working?

### ISSUE THREAD

**Issue by sdenaro** [feed2imap/feed2imap#8]
I just upgraded from 1.0.0 to 1.2.2 and noticed that include-images no longer works. 

I saw the error coming "undefined method `fetch' for HTTPFetcher:Class" being thrown from itemtomail when I enable the print statement in the rescue block.

Adding  this:

    xyzzy = HTTPFetcher.new 

Then replacing 

    image = Base64.encode64(HTTPFetcher::fetch($2, Time.at(0)).chomp) + "\n"

With 

    image = Base64.encode64(xyzzy.fetch($2, Time.at(0)).chomp) + "\n"

Fixes the problem.

I also added 

    message.header['X-Rss-Tags'] = item.categories.join(",")

below 

  message.header['X-Feed2Imap-Version'] = F2I_VERSION if defined?(F2I_VERSION)

Which puts the tags of the article in the header, making filtering by tag work in Mail.app

Let me know if I should fork and push a nicer version of this change or if you have a better solution.

Thanks

**Comment by terceiro** [comment]
Hi, sorry for the delay. This has  been fixed a while back (see 4614e1fa4ff4cb5d7442f680a053298e0cc80819). closing this issue
