### ISSUE TITLE
Noticed a problem with Yosemite Mail.App and feed2imap and I have a fix

### ISSUE THREAD

**Issue by sdenaro** [feed2imap/feed2imap#9]
I upgraded to yosemite and noticed that feeds with embedded images via include-images stopped working.  I noticed that some html mail with attachments did work. There is a subtle difference in the content id. Then I put in this simple fix:

In  `itemtomail.rb`

Change this line

              :content_id => cid,

To this

              :content_id => "<#{cid}>",

After that, everything seems to work normally. It also still works in k9 on my Android and in ios8 Mail. Didn't try it on windows. Don't know if you'll have time to fix this, but I'm putting it out in case anyone else has this problem.

**Comment by terceiro** [comment]
sorry, but I can't find any occurrence of `content_id` in `itemtomail.rb`, or even in the entire codebase. The only place where I could find `contend_id` was in an embedded copy of Net::IMAP we had, but which has been removed in commit 64455d1615ee34e03166b106f1ac33b3179fef75.

I am closing this issue for now, if you still have problems please reopen and provide more details, or open a new iseue.
